package com.lunch.ops.backend;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.jpa.repository.config.EnableJpaAuditing;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@EnableJpaAuditing
@SpringBootApplication
public class LunchOrderBackendApplication {

	public static void main(String[] args) {
		SpringApplication.run(LunchOrderBackendApplication.class, args);
	}

}
